### ISSUE TITLE
possibility of making the Activities Overview fast with this extension?

### ISSUE THREAD

**Issue by Place1** [christopher-l/instant-switcher-popups#2]
The Activities Overview on GNOME, from pressing the `super` key also has a small delay. Perhaps this extension could speed that one up as well?

**Comment by christopher-l** [comment]
Without having seen the respective code, this might be because it waits 
for the super key to be *released*, so using it as a meta key still 
works. Do you also perceive the delay when holding the key down for a 
moment and watching out for what happens when you release it, or when 
using the Alt+F1 shortcut?

**Comment by Place1** [comment]
ahh it's on key release, and I see how that's a bad idea to make it on press. oops!
